import {
  Env,
  QueryParams,
  GoogleAddressComponents,
  OdaGeocodeMetadata,
  DeferTaskFn,
  CircuitBreakerExecutor,
  CanadaPostStyleAddress,
} from './types';
import {
  getTimeoutConfig,
  getRetryConfig,
  TIME_CONSTANTS,
  TIME_CONSTANTS_SECONDS,
  QUALITY_THRESHOLDS,
} from './config';
import { runOrDefer, withRetry, withTimeout } from './utils';
import { readTimestampedEntry, writeTimestampedEntry } from './kv-cache';
import { CircuitBreakerOpenError } from './circuit-breaker';
import { isPostalOnlyQuery, wantsPostalCentroidOnly } from './geocode-query';
import {
  metricsSink,
  odaMissMetricFor,
  EXTERNAL_PROVIDER_METRIC,
  type MetricsSink,
} from './metrics';
import { safeValidateGoogleGeocode } from './validation';
import { isOdaEnabled } from './oda-config';
import {
  geocodeWithOda,
  geocodePostalCentroidWithOda,
  geocodeBatchWithOda,
  OdaGeocodeError,
  isOdaServiceFailure,
} from './oda-geocoding';
import { googleResultMatchesRegion } from './geocode-region';
import {
  buildExternalProviderChain,
  getGeocoderProvider,
  parseGoogleAddressComponents,
  runProviderChain,
  NoResultsError,
  type GeocoderProvider,
  type GeocoderProviderInput,
} from './geocoder-providers';

// Geocoding cache entry interface
interface GeocodingCacheEntry {
  lon: number;
  lat: number;
  timestamp: number;
  provider: string;
  qualifier?: string;
  score?: number;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
  geocodeMethod?: OdaGeocodeMetadata['geocodeMethod'];
  confidence?: number;
  distanceMeters?: number;
  matchedFields?: string[];
  mailingAddress?: OdaGeocodeMetadata['mailingAddress'];
  dataSource?: OdaGeocodeMetadata['dataSource'];
}

// Reverse geocoding cache entry interface
interface ReverseGeocodingCacheEntry {
  formattedAddress: string;
  components: GoogleAddressComponents;
  timestamp: number;
}

// Batch geocoding knobs. GeoGratis-first individual geocoding is the only strategy; the batch
// API road was dead and has been removed with the Google batch adapter.
const BATCH_GEOCODING_CONFIG = {
  ENABLED: true,
  MAX_BATCH_SIZE: 10,
};

// Use quality threshold from config
const GEOGRATIS_MIN_SCORE = QUALITY_THRESHOLDS.GEOGRATIS_MIN_SCORE;

/**
 * Generates a normalized cache key for geocoding requests.
 * Normalizes query parameters to ensure consistent caching.
 *
 * @param query - Query parameters (address, postal, city, state, country)
 * @param provider - Geocoding provider name (e.g., 'geogratis', 'google', 'mapbox')
 * @returns Cache key string
 */
export function generateGeocodingCacheKey(query: QueryParams, provider: string): string {
  const normalizedQuery = {
    address: query.address?.toLowerCase().trim(),
    postal: query.postal?.toLowerCase().trim().replace(/\s+/g, ''),
    city: query.city?.toLowerCase().trim(),
    state: query.state?.toLowerCase().trim(),
    country: query.country?.toLowerCase().trim()
  };

  return `geocoding:v2:${provider}:${JSON.stringify(normalizedQuery)}`;
}

/**
 * Retrieves a cached geocoding result from KV storage.
 * Validates cache entry age (24 hour TTL) and returns null if expired.
 * Does not delete expired entries - they will be cleaned up by KV TTL or when cache reaches limit.
 *
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateGeocodingCacheKey
 * @returns Cached coordinates with quality info, or null if not found/expired
 */
async function getGeocodingCacheEntry(env: Env, cacheKey: string): Promise<GeocodingCacheEntry | null> {
  return readTimestampedEntry<GeocodingCacheEntry>(
    env.GEOCODING_CACHE,
    cacheKey,
    TIME_CONSTANTS.TWENTY_FOUR_HOURS_MS,
    'geocoding result'
  );
}

export async function getCachedGeocoding(env: Env, cacheKey: string): Promise<GeocodeResult | null> {
  const cached = await getGeocodingCacheEntry(env, cacheKey);
  if (!cached) return null;
  return {
    lon: cached.lon,
    lat: cached.lat,
    normalizedAddress: cached.normalizedAddress,
    addressComponents: cached.addressComponents,
    geocodeMethod: cached.geocodeMethod,
    confidence: cached.confidence,
    distanceMeters: cached.distanceMeters,
    matchedFields: cached.matchedFields,
    mailingAddress: cached.mailingAddress,
    dataSource: cached.dataSource,
  };
}

/**
 * Stores a geocoding result in KV cache with 24-hour TTL.
 * Includes quality metadata (qualifier, score) for GeoGratis results.
 *
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateGeocodingCacheKey
 * @param result - The full geocoding result to store
 * @param provider - Geocoding provider name
 * @param qualifier - Optional quality qualifier (e.g., 'INTERPOLATED_POSITION')
 * @param score - Optional quality score (0-1 scale)
 */
export async function setCachedGeocoding(
  env: Env,
  cacheKey: string,
  result: GeocodeResult,
  provider: string,
  qualifier?: string,
  score?: number
): Promise<void> {
  const entry: GeocodingCacheEntry = {
    lon: result.lon,
    lat: result.lat,
    timestamp: Date.now(),
    provider,
    qualifier,
    score,
    normalizedAddress: result.normalizedAddress,
    addressComponents: result.addressComponents,
    geocodeMethod: result.geocodeMethod,
    confidence: result.confidence,
    distanceMeters: result.distanceMeters,
    matchedFields: result.matchedFields,
    mailingAddress: result.mailingAddress,
    dataSource: result.dataSource,
  };

  await writeTimestampedEntry(
    env.GEOCODING_CACHE,
    cacheKey,
    entry,
    TIME_CONSTANTS_SECONDS.TWENTY_FOUR_HOURS,
    'geocoding result'
  );
}

/**
 * Generates a normalized cache key for reverse geocoding requests.
 * Normalizes coordinates to ~1m precision (5 decimal places) for consistent caching.
 *
 * @param lat - Latitude
 * @param lon - Longitude
 * @returns Cache key string
 */
export function generateReverseGeocodingCacheKey(lat: number, lon: number): string {
  // Normalize coordinates to 5 decimal places (~1m precision)
  const normalizedLat = (Math.round(lat * 100000) / 100000).toString();
  const normalizedLon = (Math.round(lon * 100000) / 100000).toString();

  return `reverse:google:${normalizedLat},${normalizedLon}`;
}

/**
 * Retrieves a cached reverse geocoding result from KV storage.
 * Validates cache entry age (24 hour TTL) and returns null if expired.
 * Does not delete expired entries - they will be cleaned up by KV TTL or when cache reaches limit.
 *
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateReverseGeocodingCacheKey
 * @returns Cached reverse geocoding result, or null if not found/expired
 */
export async function getCachedReverseGeocoding(env: Env, cacheKey: string): Promise<{ formattedAddress: string; components: GoogleAddressComponents } | null> {
  const cached = await readTimestampedEntry<ReverseGeocodingCacheEntry>(
    env.GEOCODING_CACHE,
    cacheKey,
    TIME_CONSTANTS.TWENTY_FOUR_HOURS_MS,
    'reverse geocoding result'
  );
  if (!cached) return null;

  return {
    formattedAddress: cached.formattedAddress,
    components: cached.components
  };
}

/**
 * Stores a reverse geocoding result in KV cache with 24-hour TTL.
 *
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateReverseGeocodingCacheKey
 * @param result - Reverse geocoding result with formatted address and components
 */
export async function setCachedReverseGeocoding(env: Env, cacheKey: string, result: { formattedAddress: string; components: GoogleAddressComponents }): Promise<void> {
  await writeTimestampedEntry(
    env.GEOCODING_CACHE,
    cacheKey,
    {
      formattedAddress: result.formattedAddress,
      components: result.components,
      timestamp: Date.now()
    },
    TIME_CONSTANTS_SECONDS.TWENTY_FOUR_HOURS,
    'reverse geocoding result'
  );
}

export type GeocodeResult = {
  lon: number;
  lat: number;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
} & OdaGeocodeMetadata;

export type GeocodeBatchResult = {
  lon: number;
  lat: number;
  success: boolean;
  error?: string;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
  mailingAddress?: CanadaPostStyleAddress;
  geocodeMethod?: string;
  confidence?: number;
};

/** The one GeocodeResult -> GeocodeBatchResult mapper; batch paths never spread the raw result. */
function geocodeResultToBatchResult(result: GeocodeResult): GeocodeBatchResult {
  return {
    lon: result.lon,
    lat: result.lat,
    success: true,
    normalizedAddress: result.normalizedAddress,
    addressComponents: result.addressComponents,
    mailingAddress: result.mailingAddress,
    geocodeMethod: result.geocodeMethod,
    confidence: result.confidence,
  };
}

/**
 * Reverse-geocodes (lat, lon) via Google Geocoding API to obtain a normalized formatted address and components.
 * Uses X-Google-API-Key header or GOOGLE_MAPS_KEY env. Returns null if no key, ZERO_RESULTS, or error.
 * Checks cache before making API call and stores results after successful calls.
 */
export async function normalizeAddressWithGoogle(
  env: Env,
  lat: number,
  lon: number,
  request?: Request,
  circuitBreaker?: CircuitBreakerExecutor
): Promise<{ formattedAddress: string; components: GoogleAddressComponents } | null> {
  const headerKey = request?.headers.get('X-Google-API-Key');
  const key = headerKey || env.GOOGLE_MAPS_KEY;
  if (!key) return null;

  // Check cache first
  const cacheKey = generateReverseGeocodingCacheKey(lat, lon);
  const cached = await getCachedReverseGeocoding(env, cacheKey);
  if (cached) {
    return cached;
  }

  const doReverse = async (): Promise<{ formattedAddress: string; components: GoogleAddressComponents } | null> => {
    const params = new URLSearchParams({
      latlng: `${lat},${lon}`,
      key,
      region: 'ca'
    });
    const url = `https://maps.googleapis.com/maps/api/geocode/json?${params.toString()}`;
    const resp = await fetch(url, { headers: { 'User-Agent': 'riding-lookup/1.0' }, signal: AbortSignal.timeout(getTimeoutConfig(env).geocoding) });
    if (!resp.ok) throw new Error(`Google reverse geocode HTTP error: ${resp.status}`);
    const rawData = await resp.json();
    const validation = safeValidateGoogleGeocode(rawData);
    if (!validation.success) return null;
    const data = validation.data;
    if (data.status !== 'OK' || !data.results?.length) return null;

    const result = data.results[0];
    const formattedAddress = result.formatted_address;
    if (typeof formattedAddress !== 'string' || formattedAddress.length === 0) {
      return null;
    }

    const components = parseGoogleAddressComponents(result);
    if (!components) {
      // Still return formatted address even if components parsing fails
      return {
        formattedAddress,
        components: { formatted_address: formattedAddress }
      };
    }

    return { formattedAddress, components };
  };

  try {
    const timeoutConfig = getTimeoutConfig(env);
    // Reverse geocoding borrows the fallback stage ceiling; the abort above uses the overall budget.
    const timeoutMs = Math.min(timeoutConfig.geocoding, timeoutConfig.stages.fallback);
    const retryConfig = getRetryConfig();
    const fn = () => withRetry(() => withTimeout(doReverse(), timeoutMs, 'Google reverse geocode'), retryConfig, 'Google reverse geocode');
    const out = circuitBreaker
      ? await circuitBreaker.execute('geocoding:google-reverse', fn) as { formattedAddress: string; components: GoogleAddressComponents } | null
      : await fn();

    // Cache the result if successful
    if (out) {
      await setCachedReverseGeocoding(env, cacheKey, out);
    }

    return out;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// The geocoding cascade: one provider chain
//
// ODA, GeoGratis and the configured external provider are all `GeocoderProvider`s in one ordered
// chain. Each entry owns its cache key, quality gate and metrics; the chain runner is the only
// fall-through engine. ODA's miss-vs-throw contract is preserved: a postal-centroid-only query is
// terminal, while a breaker-open or a normal ODA miss falls through to the next entry.
// ---------------------------------------------------------------------------

function remainingMs(budgetMs: number, startTime: number): number {
  return Math.max(0, budgetMs - (Date.now() - startTime));
}

export function stageLimit(budgetMs: number, startTime: number, stageDefault: number): number {
  return Math.max(500, Math.min(stageDefault, remainingMs(budgetMs, startTime)));
}

/** Local ODA entry: owns the ODA cache key, breaker and miss attribution. */
const odaEntry: GeocoderProvider = {
  name: 'oda',
  async geocode(input): Promise<GeocodeResult[]> {
    const { env, qp, circuitBreaker, deferTask } = input;
    const sink = input.metrics ?? metricsSink;
    const budgetMs = input.budgetMs ?? input.timeoutMs;
    const startTime = input.startTime ?? Date.now();
    const stages = getTimeoutConfig(env).stages;

    const odaCacheKey = generateGeocodingCacheKey(qp, 'oda');
    const odaCached = await getCachedGeocoding(env, odaCacheKey);
    if (odaCached) {
      sink.incrementMetric('geocodingCacheHits');
      return [odaCached];
    }

    sink.incrementMetric('geocodingCacheMisses');
    const odaStageMs = stageLimit(budgetMs, startTime, stages.oda);
    const odaStarted = Date.now();

    const runPostalCentroid = wantsPostalCentroidOnly(qp) || isPostalOnlyQuery(qp);
    const odaFn = async (): Promise<GeocodeResult> => {
      return runPostalCentroid
        ? await geocodePostalCentroidWithOda(env, qp, undefined, sink)
        : await geocodeWithOda(env, qp, undefined, sink);
    };

    try {
      const odaPromise = circuitBreaker
        ? circuitBreaker.execute('geocoding:oda', odaFn, {
            shouldCountFailure: isOdaServiceFailure,
          })
        : odaFn();
      const odaResult = (await withTimeout(odaPromise, odaStageMs, 'ODA geocoding')) as GeocodeResult;
      sink.recordTiming('geocodingOdaTime', Date.now() - odaStarted);
      await runOrDefer(deferTask, setCachedGeocoding(env, odaCacheKey, odaResult, 'oda'));
      sink.incrementMetric('geocodingSuccesses');
      sink.recordTiming('totalGeocodingTime', Date.now() - startTime);
      return [odaResult];
    } catch (error) {
      sink.recordTiming('geocodingOdaTime', Date.now() - odaStarted);
      // A postal-centroid-only query gets one local attempt; its failure is terminal.
      if (wantsPostalCentroidOnly(qp)) {
        throw error;
      }
      if (error instanceof CircuitBreakerOpenError) {
        console.warn(
          `[GEOCODING] ODA circuit breaker open, falling back to GeoGratis/${env.GEOCODER || 'nominatim'}`
        );
        sink.incrementMetric('geocodingCircuitBreakerTrips');
      } else if (error instanceof OdaGeocodeError) {
        console.warn(
          `[GEOCODING] ODA miss (${error.code}), falling back to GeoGratis/${env.GEOCODER || 'nominatim'}`
        );
        sink.incrementMetric(odaMissMetricFor(error.code));
      } else {
        throw error;
      }
    }

    // A postal-only query gets one local attempt; if the ODA entry spent the whole budget, fail
    // rather than make an external call.
    if (isPostalOnlyQuery(qp) && remainingMs(budgetMs, startTime) <= 0) {
      throw new Error('Geocoding timeout after ' + budgetMs + 'ms');
    }
    throw new NoResultsError('oda', 'ODA did not resolve');
  },
};

/** GeoGratis entry: owns the geogratis cache key and its interpolated/poor-score gate. */
const geogratisEntry: GeocoderProvider = {
  name: 'geogratis-entry',
  async geocode(input): Promise<GeocodeResult[]> {
    const { env, qp, query, deferTask } = input;
    const sink = input.metrics ?? metricsSink;
    const budgetMs = input.budgetMs ?? input.timeoutMs;
    const startTime = input.startTime ?? Date.now();
    const stages = getTimeoutConfig(env).stages;

    const geogratisCacheKey = generateGeocodingCacheKey(qp, 'geogratis');
    const geogratisCached = await getGeocodingCacheEntry(env, geogratisCacheKey);

    if (geogratisCached) {
      const isInterpolated = geogratisCached.qualifier === 'INTERPOLATED_POSITION';
      const hasPoorScore =
        geogratisCached.score !== undefined && geogratisCached.score < GEOGRATIS_MIN_SCORE;
      const hasRegionHints = !!(qp.state || qp.city);

      if ((!isInterpolated || hasRegionHints) && !hasPoorScore) {
        sink.incrementMetric('geocodingCacheHits');
        sink.recordTiming('totalGeocodingTime', Date.now() - startTime);
        return [{ lon: geogratisCached.lon, lat: geogratisCached.lat }];
      }
      console.warn(
        `[GEOCODING] Cached GeoGratis result was ${isInterpolated ? 'interpolated' : 'poor quality'}, fetching fresh result`
      );
    }

    const geogratisStarted = Date.now();
    try {
      const geogratisStageMs = stageLimit(budgetMs, startTime, stages.geogratis);
      sink.incrementMetric('geocodingExternalCalls');
      sink.incrementMetric(EXTERNAL_PROVIDER_METRIC.geogratis);
      const adapter = getGeocoderProvider('geogratis');
      if (!adapter) throw new NoResultsError('geogratis', 'GeoGratis provider not registered');
      const candidates = await withTimeout(
        runProviderChain(
          [adapter],
          { env, qp, query, request: input.request, timeoutMs: geogratisStageMs },
          { retries: true }
        ),
        geogratisStageMs,
        'GeoGratis geocoding'
      );
      const candidate = candidates[0];
      sink.recordTiming('geocodingGeoGratisTime', Date.now() - geogratisStarted);

      const isInterpolated = candidate.qualifier === 'INTERPOLATED_POSITION';
      const hasPoorScore =
        candidate.score !== undefined && candidate.score < GEOGRATIS_MIN_SCORE;
      const hasRegionHints = !!(qp.state || qp.city);

      if (isInterpolated && !hasRegionHints) {
        console.warn(
          `[GEOCODING] GeoGratis returned INTERPOLATED_POSITION without region hints, falling back to ${env.GEOCODER || 'nominatim'}`
        );
      } else if (hasPoorScore) {
        console.warn(
          `[GEOCODING] GeoGratis returned poor score (${candidate.score}), falling back to ${env.GEOCODER || 'nominatim'}`
        );
      } else {
        await runOrDefer(
          deferTask,
          setCachedGeocoding(
            env,
            geogratisCacheKey,
            { lon: candidate.lon, lat: candidate.lat },
            'geogratis',
            candidate.qualifier,
            candidate.score
          )
        );
        sink.incrementMetric('geocodingSuccesses');
        sink.recordTiming('totalGeocodingTime', Date.now() - startTime);
        return [{ lon: candidate.lon, lat: candidate.lat }];
      }
    } catch (error) {
      sink.recordTiming('geocodingGeoGratisTime', Date.now() - geogratisStarted);
      console.warn(
        `[GEOCODING] GeoGratis error, falling back to ${env.GEOCODER || 'nominatim'}:`,
        error instanceof Error ? error.message : 'Unknown error'
      );
    }

    throw new NoResultsError('geogratis', 'GeoGratis did not resolve');
  },
};

/** External entry: the configured provider chain, with its own cache key and region gate. */
const externalEntry: GeocoderProvider = {
  name: 'external',
  async geocode(input): Promise<GeocodeResult[]> {
    const { env, qp, query, circuitBreaker, deferTask } = input;
    const sink = input.metrics ?? metricsSink;
    const budgetMs = input.budgetMs ?? input.timeoutMs;
    const startTime = input.startTime ?? Date.now();
    const stages = getTimeoutConfig(env).stages;

    // Fallback order is data: the configured provider heads the chain, followed by its
    // registered fallbacks (Google → Nominatim). The cache and breaker stay keyed by the
    // configured provider, so instrumenting and caching are unchanged.
    const chain = buildExternalProviderChain(env);
    const provider = chain[0]?.name ?? (env.GEOCODER || 'nominatim').toLowerCase();

    const cacheKey = generateGeocodingCacheKey(qp, provider);
    const cached = await getCachedGeocoding(env, cacheKey);
    if (cached) {
      const regionOk =
        provider !== 'google' ||
        googleResultMatchesRegion(qp, cached.addressComponents, cached.normalizedAddress);
      if (regionOk) {
        sink.incrementMetric('geocodingCacheHits');
        sink.recordTiming('totalGeocodingTime', Date.now() - startTime);
        // Return the full cached shape, exactly as a miss would: dropping components here made a
        // cache hit observably different from a fresh lookup.
        return [cached];
      }
      console.warn('[GEOCODING] Cached Google result outside requested region, fetching fresh result');
    }

    sink.incrementMetric('geocodingCacheMisses');
    sink.incrementMetric('geocodingExternalCalls');
    const providerMetric = EXTERNAL_PROVIDER_METRIC[provider];
    if (providerMetric) sink.incrementMetric(providerMetric);

    const fallbackStarted = Date.now();
    let result: GeocodeResult;
    try {
      const fallbackStageMs = stageLimit(budgetMs, startTime, stages.fallback);
      const fallbackPromise = runProviderChain(
        chain,
        { env, qp, query, request: input.request, timeoutMs: fallbackStageMs },
        { retries: true, circuitBreaker }
      );

      result = (await withTimeout(fallbackPromise, fallbackStageMs, 'Fallback geocoding'))[0];
      sink.recordTiming('geocodingFallbackTime', Date.now() - fallbackStarted);
      sink.incrementMetric('geocodingSuccesses');
    } catch (error) {
      sink.recordTiming('geocodingFallbackTime', Date.now() - fallbackStarted);
      console.error(`[GEOCODING] Geocoding failed after ${Date.now() - startTime}ms:`, error instanceof Error ? error.message : 'Unknown error');
      sink.incrementMetric('geocodingFailures');
      if (error instanceof CircuitBreakerOpenError) {
        console.error(`[GEOCODING] Circuit breaker is OPEN for provider: ${provider}`);
        sink.incrementMetric('geocodingCircuitBreakerTrips');
      }
      throw error;
    }

    await runOrDefer(deferTask, setCachedGeocoding(env, cacheKey, result, provider));

    sink.recordTiming('totalGeocodingTime', Date.now() - startTime);
    return [result];
  },
};

/** The cascade, in order: local ODA (when enabled), then GeoGratis, then the configured provider. */
export function buildGeocodingChain(env: Env): GeocoderProvider[] {
  const chain: GeocoderProvider[] = [];
  if (isOdaEnabled(env)) {
    chain.push(odaEntry);
  }
  chain.push(geogratisEntry);
  chain.push(externalEntry);
  return chain;
}

export type GeocodeIfNeededOptions = {
  request?: Request;
  metrics?: MetricsSink;
  circuitBreaker?: CircuitBreakerExecutor;
  deferTask?: DeferTaskFn;
};

/** Canonical shape every caller/test uses to inject or invoke geocoding. */
export type GeocodeIfNeededFn = (
  env: Env,
  query: QueryParams,
  options?: GeocodeIfNeededOptions
) => Promise<GeocodeResult>;

/**
 * The one way anything geocodes an address or postal code in this codebase.
 * Options are an object — never positional — so new knobs don't break callers.
 */
export async function geocodeIfNeeded(
  env: Env,
  qp: QueryParams,
  options: GeocodeIfNeededOptions = {}
): Promise<GeocodeResult> {
  const { request, metrics, circuitBreaker, deferTask } = options;
  const sink = metrics ?? metricsSink;

  if (typeof qp.lat === "number" && typeof qp.lon === "number") {
    return { lon: qp.lon, lat: qp.lat };
  }
  const query = qp.address || qp.postal || qp.city || qp.state || qp.country;
  if (!query) throw new Error("Missing location: provide lat/lon or address/postal");

  const timeoutConfig = getTimeoutConfig(env);
  const timeoutMs = timeoutConfig.geocoding;
  const startTime = Date.now();
  const input: GeocoderProviderInput = {
    env,
    qp,
    query,
    request,
    timeoutMs,
    metrics: sink,
    circuitBreaker,
    deferTask,
    budgetMs: timeoutMs,
    startTime,
  };

  sink.incrementMetric('geocodingRequests');

  const candidates = await withTimeout(
    runProviderChain(buildGeocodingChain(env), input),
    timeoutMs,
    "Geocoding"
  );
  const candidate = candidates[0];
  if (!candidate) throw new NoResultsError('geocoding', 'No geocoder returned results');
  return candidate;
}

export type GeocodeBatchOptions = {
  request?: Request;
  metrics?: MetricsSink;
  circuitBreaker?: CircuitBreakerExecutor;
};

/**
 * Geocodes multiple addresses with one options object, chunked to the batch size and mapped
 * through `geocodeIfNeeded`. Every item is independent; a failure is an error-shaped result,
 * never a batch abort.
 *
 * @param env - Environment bindings (API keys, KV cache)
 * @param queries - Array of query parameter objects to geocode
 * @param options - Request/metrics/breaker; an object, never positional
 * @returns Promise resolving to array of geocoding results with error information
 */
export async function geocodeBatch(
  env: Env,
  queries: QueryParams[],
  options: GeocodeBatchOptions = {}
): Promise<GeocodeBatchResult[]> {
  if (!BATCH_GEOCODING_CONFIG.ENABLED || queries.length === 0) {
    return [];
  }

  const { request, metrics, circuitBreaker } = options;
  const sink = metrics ?? metricsSink;

  if (isOdaEnabled(env)) {
    const allPostalOrCoords = queries.every(
      (q) =>
        (q.lat !== undefined && q.lon !== undefined) ||
        isPostalOnlyQuery(q) ||
        q.geocodeMethod === 'postal_centroid'
    );
    if (allPostalOrCoords) {
      const odaResults = await geocodeBatchWithOda(env, queries, sink);
      return odaResults.map((r) => ({
        lon: r.lon,
        lat: r.lat,
        success: r.success,
        error: r.error,
        normalizedAddress: r.normalizedAddress,
        geocodeMethod: r.geocodeMethod,
        confidence: r.confidence,
      }));
    }
  }

  const results: GeocodeBatchResult[] = [];
  const batchSize = BATCH_GEOCODING_CONFIG.MAX_BATCH_SIZE;

  for (let i = 0; i < queries.length; i += batchSize) {
    const batch = queries.slice(i, i + batchSize);
    for (const query of batch) {
      try {
        const result = await geocodeIfNeeded(env, query, { request, metrics: sink, circuitBreaker });
        results.push(geocodeResultToBatchResult(result));
      } catch (error) {
        results.push({
          lon: 0,
          lat: 0,
          success: false,
          error: error instanceof Error ? error.message : 'Geocoding failed'
        });
      }
    }
  }

  return results;
}

export { parseGoogleAddressComponents };
export { OdaGeocodeError } from './oda-geocoding';
