import { 
  Env, 
  QueryParams, 
  GoogleBatchGeocodeRequest,
  GoogleAddressComponents,
  GoogleGeocodeLocation,
  OdaGeocodeMetadata,
  Metrics,
  DeferTaskFn,
  CircuitBreakerExecutor,
  CanadaPostStyleAddress,
} from './types';
import { getTimeoutConfig, getRetryConfig, TIME_CONSTANTS, TIME_CONSTANTS_SECONDS, QUALITY_THRESHOLDS, GeocodingStageTimeouts } from './config';
import { runOrDefer } from './utils';
import { readTimestampedEntry, writeTimestampedEntry } from './kv-cache';
import { withRetry, withTimeout, NonRetriableError } from './utils';
import { CircuitBreakerOpenError } from './circuit-breaker';
import { isPostalOnlyQuery, wantsPostalCentroidOnly } from './geocode-query';
import { recordTiming } from './metrics';
import { 
  safeValidateGeoGratis,
  safeValidateGoogleGeocode,
  safeValidateGoogleBatchGeocode,
  safeValidateNominatim,
  safeValidateMapbox
} from './validation';
import { isOdaEnabled } from './oda-config';
import {
  geocodeWithOda,
  geocodePostalCentroidWithOda,
  geocodeBatchWithOda,
  OdaGeocodeError,
  isOdaServiceFailure,
} from './oda-geocoding';
import {
  buildGeocodeQueryString,
  expandStreetAddress,
  googleResultMatchesRegion,
  provinceNameForGoogleComponent,
  selectGeoGratisResult,
} from './geocode-region';
import { joinAddressLines } from './canada-post-format';


// Geocoding cache entry interface
interface GeocodingCacheEntry {
  lon: number;
  lat: number;
  timestamp: number;
  provider: string;
  qualifier?: string;
  score?: number;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
  geocodeMethod?: OdaGeocodeMetadata['geocodeMethod'];
  confidence?: number;
  distanceMeters?: number;
  matchedFields?: string[];
  mailingAddress?: OdaGeocodeMetadata['mailingAddress'];
  dataSource?: OdaGeocodeMetadata['dataSource'];
}

// Reverse geocoding cache entry interface
interface ReverseGeocodingCacheEntry {
  formattedAddress: string;
  components: GoogleAddressComponents;
  timestamp: number;
}

// GeoGratis-first for geolocation; normalization via Google reverse geocode when key is set.
const BATCH_GEOCODING_CONFIG = {
  ENABLED: true,
  MAX_BATCH_SIZE: 10,
  PROVIDER: 'individual' as 'individual' | 'google' // 'individual' = GeoGratis-first; 'google' = batch Google (optional fallback)
};

// Use quality threshold from config
const GEOGRATIS_MIN_SCORE = QUALITY_THRESHOLDS.GEOGRATIS_MIN_SCORE;

/**
 * Generates a normalized cache key for geocoding requests.
 * Normalizes query parameters to ensure consistent caching.
 * 
 * @param query - Query parameters (address, postal, city, state, country)
 * @param provider - Geocoding provider name (e.g., 'geogratis', 'google', 'mapbox')
 * @returns Cache key string
 */
export function generateGeocodingCacheKey(query: QueryParams, provider: string): string {
  const normalizedQuery = {
    address: query.address?.toLowerCase().trim(),
    postal: query.postal?.toLowerCase().trim().replace(/\s+/g, ''),
    city: query.city?.toLowerCase().trim(),
    state: query.state?.toLowerCase().trim(),
    country: query.country?.toLowerCase().trim()
  };
  
  return `geocoding:v2:${provider}:${JSON.stringify(normalizedQuery)}`;
}

/**
 * Retrieves a cached geocoding result from KV storage.
 * Validates cache entry age (24 hour TTL) and returns null if expired.
 * Does not delete expired entries - they will be cleaned up by KV TTL or when cache reaches limit.
 * 
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateGeocodingCacheKey
 * @returns Cached coordinates with quality info, or null if not found/expired
 */
async function getGeocodingCacheEntry(env: Env, cacheKey: string): Promise<GeocodingCacheEntry | null> {
  return readTimestampedEntry<GeocodingCacheEntry>(
    env.GEOCODING_CACHE,
    cacheKey,
    TIME_CONSTANTS.TWENTY_FOUR_HOURS_MS,
    'geocoding result'
  );
}

export async function getCachedGeocoding(env: Env, cacheKey: string): Promise<GeocodeResult | null> {
  const cached = await getGeocodingCacheEntry(env, cacheKey);
  if (!cached) return null;
  return {
    lon: cached.lon,
    lat: cached.lat,
    normalizedAddress: cached.normalizedAddress,
    addressComponents: cached.addressComponents,
    geocodeMethod: cached.geocodeMethod,
    confidence: cached.confidence,
    distanceMeters: cached.distanceMeters,
    matchedFields: cached.matchedFields,
    mailingAddress: cached.mailingAddress,
    dataSource: cached.dataSource,
  };
}

/**
 * Stores a geocoding result in KV cache with 24-hour TTL.
 * Includes quality metadata (qualifier, score) for GeoGratis results.
 * 
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateGeocodingCacheKey
 * @param lon - Longitude
 * @param lat - Latitude
 * @param provider - Geocoding provider name
 * @param qualifier - Optional quality qualifier (e.g., 'INTERPOLATED_POSITION')
 * @param score - Optional quality score (0-1 scale)
 */
export async function setCachedGeocoding(
  env: Env,
  cacheKey: string,
  result: GeocodeResult,
  provider: string,
  qualifier?: string,
  score?: number
): Promise<void> {
  const entry: GeocodingCacheEntry = {
    lon: result.lon,
    lat: result.lat,
    timestamp: Date.now(),
    provider,
    qualifier,
    score,
    normalizedAddress: result.normalizedAddress,
    addressComponents: result.addressComponents,
    geocodeMethod: result.geocodeMethod,
    confidence: result.confidence,
    distanceMeters: result.distanceMeters,
    matchedFields: result.matchedFields,
    mailingAddress: result.mailingAddress,
    dataSource: result.dataSource,
  };

  await writeTimestampedEntry(
    env.GEOCODING_CACHE,
    cacheKey,
    entry,
    TIME_CONSTANTS_SECONDS.TWENTY_FOUR_HOURS,
    'geocoding result'
  );
}

/**
 * Generates a normalized cache key for reverse geocoding requests.
 * Normalizes coordinates to ~1m precision (5 decimal places) for consistent caching.
 * 
 * @param lat - Latitude
 * @param lon - Longitude
 * @returns Cache key string
 */
export function generateReverseGeocodingCacheKey(lat: number, lon: number): string {
  // Normalize coordinates to 5 decimal places (~1m precision)
  const normalizedLat = (Math.round(lat * 100000) / 100000).toString();
  const normalizedLon = (Math.round(lon * 100000) / 100000).toString();
  
  return `reverse:google:${normalizedLat},${normalizedLon}`;
}

/**
 * Retrieves a cached reverse geocoding result from KV storage.
 * Validates cache entry age (24 hour TTL) and returns null if expired.
 * Does not delete expired entries - they will be cleaned up by KV TTL or when cache reaches limit.
 * 
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateReverseGeocodingCacheKey
 * @returns Cached reverse geocoding result, or null if not found/expired
 */
export async function getCachedReverseGeocoding(env: Env, cacheKey: string): Promise<{ formattedAddress: string; components: GoogleAddressComponents } | null> {
  const cached = await readTimestampedEntry<ReverseGeocodingCacheEntry>(
    env.GEOCODING_CACHE,
    cacheKey,
    TIME_CONSTANTS.TWENTY_FOUR_HOURS_MS,
    'reverse geocoding result'
  );
  if (!cached) return null;

  return {
    formattedAddress: cached.formattedAddress,
    components: cached.components
  };
}

/**
 * Stores a reverse geocoding result in KV cache with 24-hour TTL.
 *
 * @param env - Environment bindings containing GEOCODING_CACHE KV namespace
 * @param cacheKey - Cache key generated by generateReverseGeocodingCacheKey
 * @param result - Reverse geocoding result with formatted address and components
 */
export async function setCachedReverseGeocoding(env: Env, cacheKey: string, result: { formattedAddress: string; components: GoogleAddressComponents }): Promise<void> {
  await writeTimestampedEntry(
    env.GEOCODING_CACHE,
    cacheKey,
    {
      formattedAddress: result.formattedAddress,
      components: result.components,
      timestamp: Date.now()
    },
    TIME_CONSTANTS_SECONDS.TWENTY_FOUR_HOURS,
    'reverse geocoding result'
  );
}

// Non-retriable error removed — using NonRetriableError from './utils'

export type GeocodeResult = {
  lon: number;
  lat: number;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
} & OdaGeocodeMetadata;

export type GeocodeBatchResult = {
  lon: number;
  lat: number;
  success: boolean;
  error?: string;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
  mailingAddress?: CanadaPostStyleAddress;
  geocodeMethod?: string;
  confidence?: number;
};

function geocodeResultToBatchResult(result: GeocodeResult): GeocodeBatchResult {
  return {
    lon: result.lon,
    lat: result.lat,
    success: true,
    normalizedAddress: result.normalizedAddress,
    addressComponents: result.addressComponents,
    mailingAddress: result.mailingAddress,
    geocodeMethod: result.geocodeMethod,
    confidence: result.confidence,
  };
}

/**
 * Parses Google address_components array into structured address components object.
 * Extracts all available address parts from Google's response.
 */
export function parseGoogleAddressComponents(result: Record<string, unknown>): GoogleAddressComponents | undefined {
  if (!result || !Array.isArray(result.address_components)) {
    return undefined;
  }

  const components: GoogleAddressComponents = {};
  
  // Helper to find component by type
  const getComponent = (types: string[]): string | undefined => {
    const component = (result.address_components as Array<Record<string, unknown>>).find((comp) => 
      Array.isArray(comp.types) && types.some(type => (comp.types as string[]).includes(type))
    );
    return (component?.long_name as string) || (component?.short_name as string);
  };

  // Extract all address components
  components.street_number = getComponent(['street_number']);
  components.route = getComponent(['route']);
  components.subpremise = getComponent(['subpremise']);
  components.locality = getComponent(['locality']);
  components.administrative_area_level_1 = getComponent(['administrative_area_level_1']);
  components.administrative_area_level_2 = getComponent(['administrative_area_level_2']);
  components.administrative_area_level_3 = getComponent(['administrative_area_level_3']);
  components.administrative_area_level_4 = getComponent(['administrative_area_level_4']);
  components.administrative_area_level_5 = getComponent(['administrative_area_level_5']);
  components.country = getComponent(['country']);
  components.postal_code = getComponent(['postal_code']);
  components.postal_code_suffix = getComponent(['postal_code_suffix']);
  components.neighborhood = getComponent(['neighborhood', 'sublocality']);
  components.sublocality = getComponent(['sublocality']);
  components.sublocality_level_1 = getComponent(['sublocality_level_1']);
  components.sublocality_level_2 = getComponent(['sublocality_level_2']);
  components.sublocality_level_3 = getComponent(['sublocality_level_3']);
  components.sublocality_level_4 = getComponent(['sublocality_level_4']);
  components.sublocality_level_5 = getComponent(['sublocality_level_5']);
  components.premise = getComponent(['premise']);
  components.establishment = getComponent(['establishment']);
  components.point_of_interest = getComponent(['point_of_interest']);
  components.park = getComponent(['park']);
  components.street_address = getComponent(['street_address']);
  components.intersection = getComponent(['intersection']);
  components.political = getComponent(['political']);
  components.colloquial_area = getComponent(['colloquial_area']);
  components.ward = getComponent(['ward']);

  // Add formatted address and other metadata
  if (typeof result.formatted_address === 'string') {
    components.formatted_address = result.formatted_address;
  }
  if (typeof result.place_id === 'string') {
    components.place_id = result.place_id;
  }
  if (Array.isArray(result.types)) {
    components.types = result.types;
  }
  if (result.plus_code && typeof result.plus_code === 'object') {
    components.plus_code = result.plus_code as Record<string, string>;
  }
  const geometry = result.geometry as Record<string, unknown> | undefined;
  if (geometry?.viewport && typeof geometry.viewport === 'object') {
    components.viewport = {
      northeast: (geometry.viewport as Record<string, unknown>).northeast as GoogleGeocodeLocation,
      southwest: (geometry.viewport as Record<string, unknown>).southwest as GoogleGeocodeLocation
    };
  }
  if (geometry?.bounds && typeof geometry.bounds === 'object') {
    components.bounds = {
      northeast: (geometry.bounds as Record<string, unknown>).northeast as GoogleGeocodeLocation,
      southwest: (geometry.bounds as Record<string, unknown>).southwest as GoogleGeocodeLocation
    };
  }

  // Only return if we have at least some components
  const hasAnyComponent = Object.keys(components).some(key => 
    key !== 'formatted_address' && key !== 'place_id' && key !== 'types' && 
    key !== 'plus_code' && key !== 'viewport' && key !== 'bounds' && 
    components[key as keyof GoogleAddressComponents] !== undefined
  );

  return hasAnyComponent || components.formatted_address ? components : undefined;
}

/**
 * Reverse-geocodes (lat, lon) via Google Geocoding API to obtain a normalized formatted address and components.
 * Uses X-Google-API-Key header or GOOGLE_MAPS_KEY env. Returns null if no key, ZERO_RESULTS, or error.
 * Checks cache before making API call and stores results after successful calls.
 */
export async function normalizeAddressWithGoogle(
  env: Env,
  lat: number,
  lon: number,
  request?: Request,
  circuitBreaker?: CircuitBreakerExecutor
): Promise<{ formattedAddress: string; components: GoogleAddressComponents } | null> {
  const headerKey = request?.headers.get('X-Google-API-Key');
  const key = headerKey || env.GOOGLE_MAPS_KEY;
  if (!key) return null;

  // Check cache first
  const cacheKey = generateReverseGeocodingCacheKey(lat, lon);
  const cached = await getCachedReverseGeocoding(env, cacheKey);
  if (cached) {
    return cached;
  }

  const doReverse = async (): Promise<{ formattedAddress: string; components: GoogleAddressComponents } | null> => {
    const params = new URLSearchParams({
      latlng: `${lat},${lon}`,
      key,
      region: 'ca'
    });
    const url = `https://maps.googleapis.com/maps/api/geocode/json?${params.toString()}`;
    const resp = await fetch(url, { headers: { 'User-Agent': 'riding-lookup/1.0' }, signal: AbortSignal.timeout(getTimeoutConfig(env).geocoding) });
    if (!resp.ok) throw new Error(`Google reverse geocode HTTP error: ${resp.status}`);
    const rawData = await resp.json();
    const validation = safeValidateGoogleGeocode(rawData);
    if (!validation.success) return null;
    const data = validation.data;
    if (data.status !== 'OK' || !data.results?.length) return null;
    
    const result = data.results[0];
    const formattedAddress = result.formatted_address;
    if (typeof formattedAddress !== 'string' || formattedAddress.length === 0) {
      return null;
    }

    const components = parseGoogleAddressComponents(result);
    if (!components) {
      // Still return formatted address even if components parsing fails
      return {
        formattedAddress,
        components: { formatted_address: formattedAddress }
      };
    }

    return { formattedAddress, components };
  };

  try {
    const timeoutConfig = getTimeoutConfig(env);
    // Reverse geocoding borrows the fallback stage ceiling; the abort above uses the overall budget.
    const timeoutMs = Math.min(timeoutConfig.geocoding, timeoutConfig.stages.fallback);
    const retryConfig = getRetryConfig();
    const fn = () => withRetry(() => withTimeout(doReverse(), timeoutMs, 'Google reverse geocode'), retryConfig, 'Google reverse geocode');
    const out = circuitBreaker
      ? await circuitBreaker.execute('geocoding:google-reverse', fn) as { formattedAddress: string; components: GoogleAddressComponents } | null
      : await fn();
    
    // Cache the result if successful
    if (out) {
      await setCachedReverseGeocoding(env, cacheKey, out);
    }
    
    return out;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// GeocoderProvider seam
//
// Every outbound geocoder implements one contract: `geocode(input)` resolves to
// ranked candidates or throws a typed error. The registry is data, and the
// fallback stage walks it in order. Providers never call each other.
// ---------------------------------------------------------------------------

/** The provider was reachable but failed in a way that may succeed on retry. */
export class ProviderUnavailableError extends Error {
  readonly provider: string;
  constructor(provider: string, message: string) {
    super(message);
    this.name = 'ProviderUnavailableError';
    this.provider = provider;
  }
}

/**
 * The provider answered but had no usable match. Extends `NonRetriableError`, so
 * `withRetry` skips it and the provider chain hands off to the next entry.
 */
export class NoResultsError extends NonRetriableError {
  readonly provider: string;
  constructor(provider: string, message: string) {
    super(message);
    this.name = 'NoResultsError';
    this.provider = provider;
  }
}

/** One result from a provider, best first. */
export type GeocoderCandidate = {
  lon: number;
  lat: number;
  qualifier?: string;
  score?: number;
  normalizedAddress?: string;
  addressComponents?: GoogleAddressComponents;
};

/** Everything a provider needs. An object, so new knobs don't move every call site. */
export type GeocoderProviderInput = {
  env: Env;
  qp: QueryParams;
  query: string;
  request?: Request;
  /** Per-attempt outbound timeout (ms), derived from the stage budget. */
  timeoutMs: number;
};

/** The single contract every outbound geocoder implements. */
export interface GeocoderProvider {
  readonly name: string;
  /** Ranked candidates, best first. Throws `NoResultsError` / `ProviderUnavailableError`. */
  geocode(input: GeocoderProviderInput): Promise<GeocoderCandidate[]>;
}

type ProviderValidation<T> =
  | { success: true; data: T }
  | { success: false; error: { issues: unknown[] } };

/**
 * The one outbound protocol: fetch with the canonical user agent and timeout, reject a non-OK
 * status as unavailable, parse JSON, then zod-validate. Keeping it here means the five-line dance
 * exists once, and retry/breaker placement stays with the caller.
 */
async function fetchProviderJson<T>(
  url: string,
  opts: { provider: string; label: string; timeoutMs: number },
  validate: (data: unknown) => ProviderValidation<T>
): Promise<T> {
  const resp = await fetch(url, {
    headers: { 'User-Agent': 'riding-lookup/1.0' },
    signal: AbortSignal.timeout(opts.timeoutMs),
  });
  if (!resp.ok) {
    throw new ProviderUnavailableError(opts.provider, `${opts.label} error: ${resp.status}`);
  }
  const validation = validate(await resp.json());
  if (!validation.success) {
    console.warn(`[GEOCODING] ${opts.label} response validation failed:`, validation.error.issues);
    throw new NonRetriableError(`${opts.label} API response validation failed`);
  }
  return validation.data;
}

/**
 * GeoGratis (NRCan Geolocator): the primary service. Selection and quality scoring stay in this
 * adapter so the stage reads `qualifier`/`score` off the candidate.
 * https://www.geolocator.api.geo.ca/geolocation/en/locate
 */
const geogratisProvider: GeocoderProvider = {
  name: 'geogratis',
  async geocode({ qp, timeoutMs }) {
    const queryString = buildGeocodeQueryString(qp);
    const params = new URLSearchParams({ q: queryString, expand: 'score,component' });
    const url = `https://www.geolocator.api.geo.ca/geolocation/en/locate?${params.toString()}`;
    const data = await fetchProviderJson(
      url,
      { provider: 'geogratis', label: 'GeoGratis', timeoutMs },
      safeValidateGeoGratis
    );

    if (data.length === 0) {
      console.warn(`[GEOCODING] GeoGratis returned no results`);
      throw new NoResultsError('geogratis', 'GeoGratis returned no results');
    }

    const selected = selectGeoGratisResult(qp, data);
    if (!selected?.geometry?.coordinates || selected.geometry.coordinates.length < 2) {
      console.warn(`[GEOCODING] GeoGratis result missing valid coordinates`);
      throw new NonRetriableError('GeoGratis result missing valid coordinates');
    }

    const lon = selected.geometry.coordinates[0];
    const lat = selected.geometry.coordinates[1];
    if (typeof lon !== 'number' || typeof lat !== 'number' || isNaN(lon) || isNaN(lat)) {
      console.warn(`[GEOCODING] GeoGratis result has invalid coordinates`);
      throw new NonRetriableError('GeoGratis result has invalid coordinates');
    }

    return [{ lon, lat, qualifier: selected.qualifier, score: selected.score }];
  },
};

/**
 * Google Geocoding (BYOK via `X-Google-API-Key` or `GOOGLE_MAPS_KEY`). A miss is a typed
 * `NoResultsError`; the chain — not this adapter — decides to try Nominatim next.
 */
const googleProvider: GeocoderProvider = {
  name: 'google',
  async geocode({ qp, env, request, timeoutMs }) {
    const headerKey = request?.headers.get('X-Google-API-Key');
    const key = headerKey || env.GOOGLE_MAPS_KEY;
    if (!key) {
      throw new NonRetriableError(
        'Google API key not provided. Set X-Google-API-Key header or configure GOOGLE_MAPS_KEY environment variable'
      );
    }
    const params = new URLSearchParams({ key });
    const componentFilters: string[] = [];
    if (qp.postal) componentFilters.push(`postal_code:${qp.postal.replace(/\s+/g, '')}`);
    if (qp.city) componentFilters.push(`locality:${qp.city}`);
    const provinceComponent = provinceNameForGoogleComponent(qp.state);
    if (provinceComponent) componentFilters.push(`administrative_area:${provinceComponent}`);
    const country = (qp.country || 'CA').toUpperCase();
    componentFilters.push(`country:${country}`);
    if (componentFilters.length) params.set('components', componentFilters.join('|'));
    params.set('address', qp.address ? expandStreetAddress(qp.address) : buildGeocodeQueryString(qp));
    params.set('region', 'ca');

    const url = `https://maps.googleapis.com/maps/api/geocode/json?${params.toString()}`;
    const data = await fetchProviderJson(
      url,
      { provider: 'google', label: 'Google', timeoutMs },
      safeValidateGoogleGeocode
    );

    if (
      data.status === 'ZERO_RESULTS' ||
      data.status === 'REQUEST_DENIED' ||
      data.status === 'INVALID_REQUEST' ||
      !data.results?.length
    ) {
      console.warn(`[GEOCODING] Google API failed (${data.status || 'no results'}), trying next provider`);
      throw new NoResultsError('google', 'No results from Google');
    }
    if (data.status === 'OVER_QUERY_LIMIT' || data.status === 'UNKNOWN_ERROR') {
      throw new ProviderUnavailableError('google', `Google API error: ${data.status}`);
    }

    const result = data.results[0];
    const loc = result.geometry.location;
    const fmt = result.formatted_address;
    const components = parseGoogleAddressComponents(result);
    if (!googleResultMatchesRegion(qp, components, typeof fmt === 'string' ? fmt : undefined)) {
      console.warn('[GEOCODING] Google result outside requested region, trying next provider');
      throw new NoResultsError('google', 'No results from Google');
    }

    return [
      {
        lon: loc.lng,
        lat: loc.lat,
        ...(typeof fmt === 'string' && fmt.length > 0 && { normalizedAddress: fmt }),
        ...(components && { addressComponents: components }),
      },
    ];
  },
};

/** Nominatim (OpenStreetMap). Reached directly or as the next entry after a Google miss. */
const nominatimProvider: GeocoderProvider = {
  name: 'nominatim',
  async geocode({ qp, query, timeoutMs }) {
    const params = new URLSearchParams({ format: 'jsonv2', limit: '1', country: 'canada' });
    const street = qp.address ? expandStreetAddress(qp.address) : undefined;
    if (street) params.set('street', street);
    if (qp.city) params.set('city', qp.city);
    if (qp.state) {
      const provinceName = provinceNameForGoogleComponent(qp.state);
      params.set('state', provinceName || qp.state);
    }
    if (qp.country) params.set('country', qp.country);
    if (qp.postal) params.set('postalcode', qp.postal);
    if (![qp.address, qp.city, qp.state, qp.country, qp.postal].some(Boolean)) {
      params.set('q', query);
    }
    const url = `https://nominatim.openstreetmap.org/search?${params.toString()}`;
    const results = await fetchProviderJson(
      url,
      { provider: 'nominatim', label: 'Nominatim', timeoutMs },
      safeValidateNominatim
    );

    const first = results?.[0];
    if (!first) {
      console.error('[GEOCODING] Nominatim returned no results');
      throw new NoResultsError('nominatim', 'No results from Nominatim');
    }
    return [{ lon: Number(first.lon), lat: Number(first.lat) }];
  },
};

/** Mapbox Geocoding. */
const mapboxProvider: GeocoderProvider = {
  name: 'mapbox',
  async geocode({ query, env, timeoutMs }) {
    const token = env.MAPBOX_TOKEN;
    if (!token) throw new NonRetriableError('MAPBOX_TOKEN not configured');
    const url = `https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(query)}.json?limit=1&proximity=ca&access_token=${token}`;
    const data = await fetchProviderJson(
      url,
      { provider: 'mapbox', label: 'Mapbox', timeoutMs },
      safeValidateMapbox
    );

    const feat = data?.features?.[0];
    if (!feat?.center) throw new NoResultsError('mapbox', 'No results from Mapbox');
    return [{ lon: feat.center[0], lat: feat.center[1] }];
  },
};

/** The provider catalog. Adding a provider is one adapter plus one entry here. */
export const GEOCODER_PROVIDERS: readonly GeocoderProvider[] = [
  geogratisProvider,
  googleProvider,
  nominatimProvider,
  mapboxProvider,
];

const providerRegistry = new Map<string, GeocoderProvider>(
  GEOCODER_PROVIDERS.map((provider) => [provider.name, provider])
);

/** Register (or replace) a provider by name. Used by the contract suite's stub. */
export function registerGeocoderProvider(provider: GeocoderProvider): void {
  providerRegistry.set(provider.name, provider);
}

/** Remove a provider by name. Test cleanup only. */
export function unregisterGeocoderProvider(name: string): void {
  providerRegistry.delete(name);
}

export function getGeocoderProvider(name: string): GeocoderProvider | undefined {
  return providerRegistry.get(name.toLowerCase());
}

/**
 * Fallback order per configured provider, as data. Google's hidden Nominatim fallback is now just
 * the next entry; the adapters themselves never reach into another provider. An unlisted (or
 * registered-in-tests) name resolves to itself.
 */
const PROVIDER_FALLBACK_CHAINS: Readonly<Record<string, readonly string[]>> = {
  google: ['google', 'nominatim'],
  mapbox: ['mapbox'],
  nominatim: ['nominatim'],
};

export function buildExternalProviderChain(env: Env): GeocoderProvider[] {
  const configured = (env.GEOCODER || 'nominatim').toLowerCase();
  const names = PROVIDER_FALLBACK_CHAINS[configured] ?? [configured];
  const chain = names
    .map((name) => getGeocoderProvider(name))
    .filter((provider): provider is GeocoderProvider => Boolean(provider));
  return chain.length > 0 ? chain : [nominatimProvider];
}

/**
 * Walk a provider chain. `NoResultsError` is a miss and hands off to the next provider; any other
 * error (unavailable, misconfigured) is terminal. This is what makes fallback order data.
 */
export async function runProviderChain(
  chain: readonly GeocoderProvider[],
  input: GeocoderProviderInput
): Promise<GeocoderCandidate[]> {
  let lastMiss: NoResultsError | undefined;
  for (const provider of chain) {
    try {
      return await provider.geocode(input);
    } catch (error) {
      if (error instanceof NoResultsError) {
        lastMiss = error;
        continue;
      }
      throw error;
    }
  }
  throw lastMiss ?? new NoResultsError(chain[chain.length - 1]?.name ?? 'unknown', 'No geocoder returned results');
}

/**
 * The uniform retry/breaker wrapper. Every provider call goes through here, so failure counting
 * and retry placement do not depend on which adapter is selected.
 */
export async function executeProviderChain(
  chain: readonly GeocoderProvider[],
  input: GeocoderProviderInput,
  circuitBreaker?: CircuitBreakerExecutor
): Promise<GeocoderCandidate[]> {
  const name = chain[0]?.name ?? 'unknown';
  const retryConfig = getRetryConfig();
  const attempt = () => withRetry(() => runProviderChain(chain, input), retryConfig, `Geocoding ${name}`);
  if (!circuitBreaker) return attempt();
  return (await circuitBreaker.execute(`geocoding:${name}`, attempt)) as GeocoderCandidate[];
}

function candidateToGeocodeResult(candidate: GeocoderCandidate): GeocodeResult {
  return {
    lon: candidate.lon,
    lat: candidate.lat,
    ...(candidate.normalizedAddress && { normalizedAddress: candidate.normalizedAddress }),
    ...(candidate.addressComponents && { addressComponents: candidate.addressComponents }),
  };
}

/**
 * Fallback instrumentation. A local miss is attributed to its contract code so the rate can be
 * broken down by cause; external calls are counted per provider so spend and health are visible.
 * See docs/plans/reduce-external-geocoder-fallback.md.
 */
const ODA_MISS_METRIC: Record<string, keyof Metrics> = {
  ADDRESS_NOT_FOUND: 'geocodingOdaMissNotFound',
  AMBIGUOUS_LOCATION: 'geocodingOdaMissAmbiguous',
  PROVINCE_NOT_LOADED: 'geocodingOdaMissProvinceNotLoaded',
  LOW_CONFIDENCE_GEOCODE: 'geocodingOdaMissLowConfidence',
};

const EXTERNAL_PROVIDER_METRIC: Record<string, keyof Metrics> = {
  google: 'geocodingExternalGoogle',
  mapbox: 'geocodingExternalMapbox',
  nominatim: 'geocodingExternalNominatim',
};

function remainingMs(budgetMs: number, startTime: number): number {
  return Math.max(0, budgetMs - (Date.now() - startTime));
}

export function stageLimit(budgetMs: number, startTime: number, stageDefault: number): number {
  return Math.max(500, Math.min(stageDefault, remainingMs(budgetMs, startTime)));
}

export type GeocodeStageContext = {
  env: Env;
  qp: QueryParams;
  query: string;
  request?: Request;
  metrics?: GeocodingMetricsSink;
  circuitBreaker?: CircuitBreakerExecutor;
  deferTask?: DeferTaskFn;
  /** Overall geocoding budget for this request (ms). */
  budgetMs: number;
  /** Epoch ms when the cascade started; stage limits are derived from the remaining budget. */
  startTime: number;
  /** Per-stage ceilings within the overall budget, from `getTimeoutConfig().stages`. */
  stages: GeocodingStageTimeouts;
};

/**
 * One step of the geocoding cascade. Returning `null` means "miss, try the next stage"; throwing
 * is terminal. Each stage owns its own cache key and write, so ordering is data, not control flow.
 */
export type GeocodeStage = (ctx: GeocodeStageContext) => Promise<GeocodeResult | null>;

export async function runOdaGeocodeStage(ctx: GeocodeStageContext): Promise<GeocodeResult | null> {
  const { env, qp, circuitBreaker, deferTask, metrics, budgetMs, startTime, stages } = ctx;

  const odaCacheKey = generateGeocodingCacheKey(qp, 'oda');
  const odaCached = await getCachedGeocoding(env, odaCacheKey);
  if (odaCached) {
    metrics?.incrementMetric('geocodingCacheHits');
    return odaCached;
  }

  metrics?.incrementMetric('geocodingCacheMisses');
  const odaStageMs = stageLimit(budgetMs, startTime, stages.oda);
  const odaStarted = Date.now();

  const runPostalCentroid = wantsPostalCentroidOnly(qp) || isPostalOnlyQuery(qp);
  const odaFn = async (): Promise<GeocodeResult> => {
    const result = runPostalCentroid
      ? await geocodePostalCentroidWithOda(env, qp)
      : await geocodeWithOda(env, qp);
    return result;
  };

  try {
    const odaPromise = circuitBreaker
      ? circuitBreaker.execute('geocoding:oda', odaFn, {
          shouldCountFailure: isOdaServiceFailure,
        })
      : odaFn();
    const odaResult = (await withTimeout(odaPromise, odaStageMs, 'ODA geocoding')) as GeocodeResult;
    recordTiming('geocodingOdaTime', Date.now() - odaStarted);
    await runOrDefer(deferTask, setCachedGeocoding(env, odaCacheKey, odaResult, 'oda'));
    metrics?.incrementMetric('geocodingSuccesses');
    metrics?.recordTiming('totalGeocodingTime', Date.now() - startTime);
    return odaResult;
  } catch (error) {
    recordTiming('geocodingOdaTime', Date.now() - odaStarted);
    if (wantsPostalCentroidOnly(qp)) {
      throw error;
    }
    if (error instanceof CircuitBreakerOpenError) {
      console.warn(
        `[GEOCODING] ODA circuit breaker open, falling back to GeoGratis/${env.GEOCODER || 'nominatim'}`
      );
      metrics?.incrementMetric('geocodingCircuitBreakerTrips');
    } else if (error instanceof OdaGeocodeError) {
      console.warn(
        `[GEOCODING] ODA miss (${error.code}), falling back to GeoGratis/${env.GEOCODER || 'nominatim'}`
      );
      metrics?.incrementMetric(ODA_MISS_METRIC[error.code] ?? 'geocodingOdaMissOther');
    } else {
      throw error;
    }
  }

  // A postal-only query gets one local attempt; if the ODA stage spent the whole budget, fail
  // rather than make an external call. (Postal-centroid-only already threw above.)
  if (isPostalOnlyQuery(qp) && remainingMs(budgetMs, startTime) <= 0) {
    throw new Error('Geocoding timeout after ' + budgetMs + 'ms');
  }
  return null;
}

export async function runGeoGratisStage(ctx: GeocodeStageContext): Promise<GeocodeResult | null> {
  const { env, qp, query, deferTask, metrics, budgetMs, startTime, stages } = ctx;

  const geogratisCacheKey = generateGeocodingCacheKey(qp, 'geogratis');
  const geogratisCached = await getGeocodingCacheEntry(env, geogratisCacheKey);

  if (geogratisCached) {
    const isInterpolated = geogratisCached.qualifier === 'INTERPOLATED_POSITION';
    const hasPoorScore =
      geogratisCached.score !== undefined && geogratisCached.score < GEOGRATIS_MIN_SCORE;
    const hasRegionHints = !!(qp.state || qp.city);

    if ((!isInterpolated || hasRegionHints) && !hasPoorScore) {
      metrics?.incrementMetric('geocodingCacheHits');
      metrics?.recordTiming('totalGeocodingTime', Date.now() - startTime);
      return { lon: geogratisCached.lon, lat: geogratisCached.lat };
    } else {
      console.warn(
        `[GEOCODING] Cached GeoGratis result was ${isInterpolated ? 'interpolated' : 'poor quality'}, fetching fresh result`
      );
    }
  }

  // Try GeoGratis API
  const geogratisStarted = Date.now();
  try {
    const geogratisStageMs = stageLimit(budgetMs, startTime, stages.geogratis);
    metrics?.incrementMetric('geocodingExternalCalls');
    metrics?.incrementMetric('geocodingExternalGeogratis');
    const geogratisCandidates = await withTimeout(
      executeProviderChain([geogratisProvider], { env, qp, query, timeoutMs: geogratisStageMs }),
      geogratisStageMs,
      'GeoGratis geocoding'
    );
    const geogratisResult = geogratisCandidates[0];
    recordTiming('geocodingGeoGratisTime', Date.now() - geogratisStarted);

    if (geogratisResult) {
      const isInterpolated = geogratisResult.qualifier === 'INTERPOLATED_POSITION';
      const hasPoorScore =
        geogratisResult.score !== undefined && geogratisResult.score < GEOGRATIS_MIN_SCORE;
      const hasRegionHints = !!(qp.state || qp.city);

      if (isInterpolated && !hasRegionHints) {
        console.warn(
          `[GEOCODING] GeoGratis returned INTERPOLATED_POSITION without region hints, falling back to ${env.GEOCODER || 'nominatim'}`
        );
      } else if (hasPoorScore) {
        console.warn(
          `[GEOCODING] GeoGratis returned poor score (${geogratisResult.score}), falling back to ${env.GEOCODER || 'nominatim'}`
        );
      } else {
        await runOrDefer(
          deferTask,
          setCachedGeocoding(
            env,
            geogratisCacheKey,
            { lon: geogratisResult.lon, lat: geogratisResult.lat },
            'geogratis',
            geogratisResult.qualifier,
            geogratisResult.score
          )
        );
        metrics?.incrementMetric('geocodingSuccesses');
        metrics?.recordTiming('totalGeocodingTime', Date.now() - startTime);
        return { lon: geogratisResult.lon, lat: geogratisResult.lat } as GeocodeResult;
      }
    } else {
      // GeoGratis failed
      console.warn(`[GEOCODING] GeoGratis failed, falling back to ${env.GEOCODER || 'nominatim'}`);
    }
  } catch (error) {
    recordTiming('geocodingGeoGratisTime', Date.now() - geogratisStarted);
    // GeoGratis threw an error
    console.warn(`[GEOCODING] GeoGratis error, falling back to ${env.GEOCODER || 'nominatim'}:`, error instanceof Error ? error.message : 'Unknown error');
  }

  return null;
}

export async function runExternalFallbackStage(ctx: GeocodeStageContext): Promise<GeocodeResult | null> {
  const { env, qp, query, request, metrics, circuitBreaker, deferTask, budgetMs, startTime, stages } = ctx;

  const fallbackStarted = Date.now();
  // Fallback order is data: the configured provider heads the chain, followed by its
  // registered fallbacks (Google → Nominatim). The cache and breaker stay keyed by the
  // configured provider, so instrumenting and caching are unchanged.
  const chain = buildExternalProviderChain(env);
  const provider = chain[0]?.name ?? (env.GEOCODER || "nominatim").toLowerCase();

  // Check cache for fallback provider
  const cacheKey = generateGeocodingCacheKey(qp, provider);
  const cached = await getCachedGeocoding(env, cacheKey);
  if (cached) {
    const regionOk =
      provider !== 'google' ||
      googleResultMatchesRegion(qp, cached.addressComponents, cached.normalizedAddress);
    if (regionOk) {
      metrics?.incrementMetric('geocodingCacheHits');
      metrics?.recordTiming('totalGeocodingTime', Date.now() - startTime);
      return { lon: cached.lon, lat: cached.lat } as GeocodeResult;
    }
    console.warn('[GEOCODING] Cached Google result outside requested region, fetching fresh result');
  }

  metrics?.incrementMetric('geocodingCacheMisses');

  // Use circuit breaker and retry for geocoding
  metrics?.incrementMetric('geocodingExternalCalls');
  const providerMetric = EXTERNAL_PROVIDER_METRIC[provider];
  if (providerMetric) metrics?.incrementMetric(providerMetric);

  let result: GeocodeResult;
  try {
    const fallbackStageMs = stageLimit(budgetMs, startTime, stages.fallback);
    const input: GeocoderProviderInput = { env, qp, query, request, timeoutMs: fallbackStageMs };
    const fallbackPromise = executeProviderChain(chain, input, circuitBreaker);

    result = candidateToGeocodeResult((await withTimeout(fallbackPromise, fallbackStageMs, 'Fallback geocoding'))[0]);
    recordTiming('geocodingFallbackTime', Date.now() - fallbackStarted);

    metrics?.incrementMetric('geocodingSuccesses');
  } catch (error) {
    recordTiming('geocodingFallbackTime', Date.now() - fallbackStarted);
    console.error(`[GEOCODING] Geocoding failed after ${Date.now() - startTime}ms:`, error instanceof Error ? error.message : 'Unknown error');
    metrics?.incrementMetric('geocodingFailures');
    if (error instanceof CircuitBreakerOpenError) {
      console.error(`[GEOCODING] Circuit breaker is OPEN for provider: ${provider}`);
      metrics?.incrementMetric('geocodingCircuitBreakerTrips');
    }
    throw error;
  }

  // Cache the result
  await runOrDefer(deferTask, setCachedGeocoding(env, cacheKey, result, provider));

  metrics?.recordTiming('totalGeocodingTime', Date.now() - startTime);
  return result;
}

/**
 * Executes stages in order. The first stage that returns a result wins; `null` falls through and a
 * throw is terminal. Order is data, so callers and tests can rearrange or stub the sequence.
 */
export async function runGeocodeStages(
  ctx: GeocodeStageContext,
  stages: readonly GeocodeStage[]
): Promise<GeocodeResult> {
  for (const stage of stages) {
    const result = await stage(ctx);
    if (result) return result;
  }
  throw new Error('All geocoding stages missed');
}

/** The cascade, in order: local ODA (when enabled), then GeoGratis, then the configured provider. */
export function buildGeocodeStages(env: Env): GeocodeStage[] {
  const stages: GeocodeStage[] = [];
  if (isOdaEnabled(env)) {
    stages.push(runOdaGeocodeStage);
  }
  stages.push(runGeoGratisStage);
  stages.push(runExternalFallbackStage);
  return stages;
}

// Main geocoding function
/**
 * Geocodes a query (address/postal code) to coordinates if needed.
 * Uses cached results when available, with quality-aware caching for GeoGratis.
 * Falls back through multiple providers: GeoGratis -> Google -> Mapbox -> Nominatim.
 * When Google is used for forward geocoding, returns normalizedAddress (formatted_address).
 * 
 * @param env - Environment bindings (API keys, KV cache)
 * @param query - Query parameters (address, postal, city, state, country)
 * @param request - Optional request object for extracting Google API key from headers
 * @returns Promise resolving to {lon, lat, normalizedAddress?} coordinates
 * @throws Error if geocoding fails for all providers
 */
export type GeocodingMetricsSink = {
  incrementMetric: (key: keyof Metrics, value?: number) => void;
  recordTiming: (key: keyof Metrics, duration: number) => void;
};

export type GeocodeIfNeededOptions = {
  request?: Request;
  metrics?: GeocodingMetricsSink;
  circuitBreaker?: CircuitBreakerExecutor;
  deferTask?: DeferTaskFn;
};

/** Canonical shape every caller/test uses to inject or invoke geocoding. */
export type GeocodeIfNeededFn = (
  env: Env,
  query: QueryParams,
  options?: GeocodeIfNeededOptions
) => Promise<GeocodeResult>;

/**
 * The one way anything geocodes an address or postal code in this codebase.
 * Options are an object — never positional — so new knobs don't break callers.
 */
export async function geocodeIfNeeded(
  env: Env,
  qp: QueryParams,
  options: GeocodeIfNeededOptions = {}
): Promise<GeocodeResult> {
  const { request, metrics, circuitBreaker, deferTask } = options;

  if (typeof qp.lat === "number" && typeof qp.lon === "number") {
    return { lon: qp.lon, lat: qp.lat };
  }
  const query = qp.address || qp.postal || qp.city || qp.state || qp.country;
  if (!query) throw new Error("Missing location: provide lat/lon or address/postal");

  const timeoutConfig = getTimeoutConfig(env);
  const timeoutMs = timeoutConfig.geocoding;
  const ctx: GeocodeStageContext = {
    env,
    qp,
    query,
    request,
    metrics,
    circuitBreaker,
    deferTask,
    budgetMs: timeoutMs,
    startTime: Date.now(),
    stages: timeoutConfig.stages,
  };

  metrics?.incrementMetric('geocodingRequests');

  return withTimeout(runGeocodeStages(ctx, buildGeocodeStages(env)), timeoutMs, "Geocoding");
}

// Batch geocoding with Google
export async function geocodeBatchWithGoogle(
  env: Env, 
  queries: QueryParams[], 
  apiKey: string
): Promise<GeocodeBatchResult[]> {
  const results: GeocodeBatchResult[] = [];
  const errors: string[] = [];
  
  // Convert queries to Google batch format. Parts are joined by the one canonical assembler;
  // the Google batch API takes the province code and country as given, so no expansion is applied.
  const addresses = queries.map(query => ({
    address: joinAddressLines([query.address, query.postal, query.city, query.state, query.country]),
  }));

  const batchRequest: GoogleBatchGeocodeRequest = {
    addresses
  };

  try {
    const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': 'riding-lookup/1.0'
      },
      body: JSON.stringify(batchRequest),
      signal: AbortSignal.timeout(getTimeoutConfig(env).geocoding)
    });

    if (!response.ok) {
      const errorMsg = `Google batch geocoding HTTP error: ${response.status}`;
      errors.push(errorMsg);
      // Return failures for all queries
      for (let i = 0; i < queries.length; i++) {
        results.push({ lon: 0, lat: 0, success: false, error: errorMsg });
      }
      return results;
    }
    
    const rawData = await response.json();
    // Validate batch response structure
    const validation = safeValidateGoogleBatchGeocode(rawData);
    if (!validation.success) {
      const errorMsg = `Google batch geocoding validation failed: ${validation.error.issues.map(e => e.message).join(', ')}`;
      console.warn(`[GEOCODING] ${errorMsg}`);
      errors.push(errorMsg);
      // Return failures for all queries
      for (let i = 0; i < queries.length; i++) {
        results.push({ lon: 0, lat: 0, success: false, error: errorMsg });
      }
      return results;
    }
    
    const data = validation.data;
    
    if (data.results && data.results.length === queries.length) {
      // Process batch results
      let successCount = 0;
      let failureCount = 0;
      
      for (let i = 0; i < data.results.length; i++) {
        const result = data.results[i];
        const query = queries[i];
        
        if (result.geometry?.location) {
          // Parse address components if available in batch response
          // Note: Google batch API may have different structure, so we try to extract what we can
          const addressComponents = result.address_components 
            ? parseGoogleAddressComponents({ 
                address_components: result.address_components, 
                formatted_address: result.geocoded_address, 
                place_id: result.place_id, 
                types: result.types,
                geometry: result.geometry
              })
            : undefined;
          
          results.push({
            lon: result.geometry.location.lng,
            lat: result.geometry.location.lat,
            success: true,
            ...(result.geocoded_address && { normalizedAddress: result.geocoded_address }),
            ...(addressComponents && { addressComponents })
          });
          successCount++;
        } else {
          const errorMsg = `No results for query: ${query.address || query.postal || query.city || 'unknown'}`;
          results.push({
            lon: 0,
            lat: 0,
            success: false,
            error: errorMsg
          });
          errors.push(`Query ${i}: ${errorMsg}`);
          failureCount++;
        }
      }
      
      if (failureCount > 0) {
        console.warn(`Batch geocoding: ${successCount} succeeded, ${failureCount} failed out of ${queries.length} total`);
      }
    } else {
      // Batch response doesn't match query count - fallback to individual
      const errorMsg = `Batch response mismatch: expected ${queries.length} results, got ${data.results?.length || 0}`;
      errors.push(errorMsg);
      console.warn(errorMsg + ', falling back to individual geocoding');
      
      // Fallback to individual geocoding
      for (let i = 0; i < queries.length; i++) {
        const query = queries[i];
        try {
          const result = await geocodeIfNeeded(env, query);
          results.push({ ...result, success: true });
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : 'Geocoding failed';
          results.push({
            lon: 0,
            lat: 0,
            success: false,
            error: errorMsg
          });
          errors.push(`Query ${i}: ${errorMsg}`);
        }
      }
    }
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : 'Unknown error';
    console.error('Google batch geocoding failed:', errorMsg);
    errors.push(`Batch API error: ${errorMsg}`);
    
    // Fallback to individual geocoding
    for (let i = 0; i < queries.length; i++) {
      const query = queries[i];
      try {
        const result = await geocodeIfNeeded(env, query);
        results.push({ ...result, success: true });
      } catch (individualError) {
        const errorMsg = individualError instanceof Error ? individualError.message : 'Geocoding failed';
        results.push({
          lon: 0,
          lat: 0,
          success: false,
          error: errorMsg
        });
        errors.push(`Query ${i}: ${errorMsg}`);
      }
    }
  }

  // Log aggregated errors if any
  if (errors.length > 0) {
    console.warn(`Batch geocoding errors (${errors.length}):`, errors.slice(0, 5)); // Log first 5 errors
  }

  return results;
}

// Batch geocoding function
/**
 * Geocodes multiple addresses, using batch API when available or falling back to individual requests.
 * Automatically selects the best geocoding strategy based on configuration.
 * 
 * @param env - Environment bindings (API keys, KV cache)
 * @param queries - Array of query parameter objects to geocode
 * @param request - Optional request object for extracting Google API key
 * @returns Promise resolving to array of geocoding results with error information
 */
export async function geocodeBatch(
  env: Env, 
  queries: QueryParams[], 
  request?: Request,
  metrics?: {
    incrementMetric: (key: keyof Metrics, value?: number) => void;
    recordTiming: (key: keyof Metrics, duration: number) => void;
  },
  circuitBreaker?: CircuitBreakerExecutor
): Promise<GeocodeBatchResult[]> {
  if (!BATCH_GEOCODING_CONFIG.ENABLED || queries.length === 0) {
    return [];
  }

  if (isOdaEnabled(env)) {
    const allPostalOrCoords = queries.every(
      (q) =>
        (q.lat !== undefined && q.lon !== undefined) ||
        isPostalOnlyQuery(q) ||
        q.geocodeMethod === 'postal_centroid'
    );
    if (allPostalOrCoords) {
      const odaResults = await geocodeBatchWithOda(env, queries);
      return odaResults.map((r) => ({
        lon: r.lon,
        lat: r.lat,
        success: r.success,
        error: r.error,
        normalizedAddress: r.normalizedAddress,
        geocodeMethod: r.geocodeMethod,
        confidence: r.confidence,
      }));
    }
  }

  const results: GeocodeBatchResult[] = [];
  
  // Process in batches
  const batchSize = BATCH_GEOCODING_CONFIG.MAX_BATCH_SIZE;
  for (let i = 0; i < queries.length; i += batchSize) {
    const batch = queries.slice(i, i + batchSize);
    
    try {
      if (BATCH_GEOCODING_CONFIG.PROVIDER === 'google' && env.GOOGLE_MAPS_KEY) {
        const batchResults = await geocodeBatchWithGoogle(env, batch, env.GOOGLE_MAPS_KEY);
        results.push(...batchResults);
      } else {
        // GeoGratis-first individual geocoding
        for (const query of batch) {
          try {
            const result = await geocodeIfNeeded(env, query, { request, metrics, circuitBreaker });
            results.push(geocodeResultToBatchResult(result));
          } catch (error) {
            results.push({
              lon: 0,
              lat: 0,
              success: false,
              error: error instanceof Error ? error.message : 'Geocoding failed'
            });
          }
        }
      }
    } catch (error) {
      console.error(`Batch geocoding failed for batch ${i / BATCH_GEOCODING_CONFIG.MAX_BATCH_SIZE + 1}:`, error);

      for (const query of batch) {
        try {
          const result = await geocodeIfNeeded(env, query, { request, metrics, circuitBreaker });
          results.push(geocodeResultToBatchResult(result));
        } catch (individualError) {
          results.push({
            lon: 0,
            lat: 0,
            success: false,
            error: individualError instanceof Error ? individualError.message : 'Geocoding failed'
          });
        }
      }
    }
  }

  return results;
}

export { OdaGeocodeError } from './oda-geocoding';
